default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:

development:
  <<: *default
  host: db
  database: app_development
test:
  <<: *default
  host: <%= ENV['DB_HOST'] || 'db' %>
  database: app_test

production:
  <<: *default
  database: app_production
  url: <%= ENV['DATABASE_URL'] %>
