inherit_from: .rubocop_todo.yml

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Max: 80
  Exclude:
    - "spec/**/*"

Style/AsciiComments:
  Enabled: false

Metrics/LineLength:
  Max: 140

Lint/UselessAssignment:
  Exclude:
    - "spec/**/*"

AllCops:
  DisabledByDefault: true
  Exclude:
    - "gems/**/*"
  NewCops: enable
