# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.0.1'

gem 'rails', '~> 6.1.3', '>= 6.1.3.1'

gem 'mysql2', '~> 0.5'

gem 'puma', '~> 5.0'

gem 'msgpack', '~>1.4.2'

gem 'bootsnap', '>= 1.4.4', require: false

gem 'rack-cors'

gem 'firebase-auth-rails'

gem 'jwt'

gem 'carrierwave'

gem 'carrierwave-base64'

gem 'fog'

group :development, :test do
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'rspec-rails'
  gem 'rubocop', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rails', require: false
  gem 'rubocop-rspec'
end

group :development do
  gem 'listen', '~> 3.3'
  gem 'spring'
end

gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
