swagger: "2.0"

info:
  description: Tell MeのAPI仕様です。
  version: "0.0.0"
  title: Tell Me
paths:
  /daycares/:id:
    get:
      tags:
        - "daycares"
      summary: "IDに紐づいた保育園のレコード取得"
      description: ""
      parameters:
        - name: daycare_id
          in: path
          description: 特定の子供の名前と年齢を取得
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: 成功時のレスポンス
          schema:
            title: 保育園のレコード返却
            type: object
            properties:
              id:
                type: integer
              name:
                type: string
              address:
                type: string
              telephone_number:
                type: string
        404:
          description: "該当する保育園が見つからない"
          schema:
            $ref: "#/definitions/404Error"
  /daycares/:daycare_id/users/:id/posts:
    get:
      tags:
        - "posts"
      summary: "ある保育園の先生の投稿を全て取得"
      description: ""
      parameters:
        - name: daycare_id
          in: path
          description: 保育園のID
          required: true
          type: integer
          format: int64
        - name: id
          in: path
          description: ユーザーのID
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: "成功時のレスポンス"
          schema:
            type: array
            $ref: "#/definitions/Post"
        404:
          description: "該当する投稿が見つからない"
          schema:
            $ref: "#/definitions/404Error"
    post:
      tags:
        - "posts"
      summary: "ある保育園の先生の投稿を作成"
      description: ""
      parameters:
        - name: daycare_id
          in: path
          description: 保育園のID
          required: true
          type: integer
          format: int64
        - name: id
          in: path
          description: 子供のID
          required: true
          type: integer
          format: int64
        - in: "body"
          name: "body"
          description: "投稿者と投稿内容"
          required: true
          schema:
            title: 投稿
            type: object
            properties:
              poster:
                type: string
              content:
                type: string
      responses:
        200:
          description: "成功時のレスポンス"
          schema:
            type: array
            $ref: "#/definitions/Post"
        400:
          description: "投稿内容に不備"
          schema:
            $ref: "#/definitions/404Error"
  /daycares/:daycare_id/posts:
    get:
      tags:
        - "posts"
      summary: "ある保育園の全ての投稿取得"
      description: ""
      parameters:
        - name: daycare_id
          in: path
          description: 保育園のID
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: "成功時のレスポンス"
          schema:
            type: array
            $ref: "#/definitions/Post"
        404:
          description: "該当する投稿が見つからない"
          schema:
            $ref: "#/definitions/404Error"
  /daycares/:id/kids:
    get:
      tags:
        - "kids"
      summary: "ある保育園の子供のデータを全て取得"
      description: ""
      parameters:
        - name: daycare_id
          in: path
          description: 保育園のID
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: "成功時のレスポンス"
          schema:
            type: array
            $ref: "#/definitions/Kid"
        404:
          description: "該当する子供が見つからない"
          schema:
            $ref: "#/definitions/404Error"

  /users/:id/kids:
    post:
      tags:
        - "kids"
      summary: "ある親の子供を全て取得"
      description: ""
      parameters:
        - name: id
          in: path
          description: ユーザーのID
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: "成功時のレスポンス"
          schema:
            $ref: "#/definitions/Kid"
        404:
          description: "該当する子供が見つからない"
          schema:
            $ref: "#/definitions/404Error"
  /kids/:id/fetch_posts:
    post:
      tags:
        - "kids"
      summary: "ある子供が通っている保育園の投稿を全て取得"
      description: ""
      parameters:
        - name: id
          in: path
          description: ユーザーのID
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: "成功時のレスポンス"
          schema:
            $ref: "#/definitions/Kid"
        404:
          description: "該当する子供が見つからない"
          schema:
            $ref: "#/definitions/404Error"
definitions:
  Notebook:
    type: object
    properties:
      id:
        type: integer
      kid_id:
        type: integer
      date:
        type: string
      body_temperature:
        type: integer
      has_bathed:
        type: boolean
      breakfast:
        type: string
      dinner:
        type: string
      memo:
        type: string
      created_at:
        type: string
      updated_at:
        type: string
  Kid:
    type: object
    properties:
      id:
        type: integer
      first_name:
        type: string
      last_name:
        type: string
      age:
        type: integer
      gender:
        type: integer
      favorite_food:
        type: string
      favorite_play:
        type: string
      image:
        type: string
      created_at:
        type: string
      updated_at:
        type: string
  User:
    type: object
    properties:
      id:
        type: integer
      first_name:
        type: string
      last_name:
        type: string
      email:
        type: string
      gender:
        type: integer
      telephone_number:
        type: string
      password:
        type: string
      role:
        type: string
      image:
        type: string
      created_at:
        type: string
      updated_at:
        type: string
  Daycare:
    type: object
    properties:
      id:
        type: integer
      address:
        type: string
      telephone_number:
        type: string
      name:
        type: string
      created_at:
        type: string
      updated_at:
        type: string
  Post:
    type: object
    properties:
      id:
        type: integer
      daycare_id:
        type: integer
      user_id:
        type: integer
      content:
        type: string
      poster:
        type: string
      created_at:
        type: string
      updated_at:
        type: string
  404Error:
    type: "object"
    properties:
      status:
        type: "integer"
        example: "404"
        format: "int64"
      message:
        type: "string"
        example: "データが見つかりません"
  400NoInputError:
    type: "object"
    properties:
      status:
        type: "integer"
        example: "400"
        format: "int64"
      message:
        type: "string"
        example: "未入力箇所があります"
