name: "Codecov"

on: push

jobs:
  upload-reports:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@master
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          name: codecov-umbrella # optional
          directory: backend/coverage
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
