name: "Codecov"

on:
  push:
    branches:
      - develop

jobs:
  upload-reports:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@master
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          files: ./backend/coverage/codecov-result.json.
          name: codecov-umbrella # optional
          directory: backend/coverage
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
