name: "Codecov"

on:
  push:
    branches:
      - develop

jobs:
  upload-reports:
    runs-on: ubuntu-latest
    steps:
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./backend/coverage/codecov-result.json.
          name: codecov-umbrella
          directory: backend/coverage
          fail_ci_if_error: true
          verbose: true
